# -*- coding: utf-8 -*-
"""DCMforMulticoncept.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDdDn2KA4ReUIn2X7QJzc-6_rsHNryKG

# Main
"""

import pandas as pd
import csv
import numpy as np
from google.colab import drive
from sklearn.ensemble import RandomForestRegressor


drive.mount('/content/gdrive')
df = pd.read_csv('/content/iris0-5-1tra.dat', sep=',',skiprows=9, names=['A','B','C','D','Z'])
df.sort_values('Z')


dataToClusters(df,label=[' positive',' negative'],nC=4,k=3)



"""# Synthetic datasets"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import KFold
from sklearn.svm import LinearSVC
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score


def getGMeanAccAUC(y_test,y_pred,y_prob):

  #print(y_test,y_pred)
# Creating the confusion matrix
  conf_matrix = metrics.confusion_matrix(y_test, y_pred)
# Assigning columns names
 # conf_matrix_df = pd.DataFrame(conf_matrix, columns = ['Predicted Negative', 'Predicted Positive'],  index = ['Actual Negative', 'Actual Positive'])
  if(len(conf_matrix)==1):
     GMean=conf_matrix[0][0]/len(y_test)
  else:

# Showing the confusion matrix
    TP = conf_matrix[1][1]
    TN = conf_matrix[0][0]
    FP = conf_matrix[0][1]
    FN = conf_matrix[1][0]
    RecallP = (TP / float(TP + FN))
    RecallN = (TN / float(TN + FP))
    GMean= (RecallP*RecallN)**0.5
  auc = roc_auc_score(y_test, y_prob)
  #auc=0
  acc=accuracy_score(y_test,y_pred)
  return GMean,acc,auc



datasize=200
InstanceNoInClass=datasize//2;
np.random.normal()
y=eval('np.random.normal(4,2,size=[InstanceNoInClass//2,2])')
yy=eval('np.random.normal(16,4,size=[InstanceNoInClass//2,2])')
y=np.concatenate([y,yy])
kf = KFold(n_splits=5,shuffle=True,random_state=1)


A=y[:,0]
B=y[:,1]
plt.scatter(A,B,marker='*',label='class A')

YY=eval('np.random.normal(16,4,size=[InstanceNoInClass//2,2])')
Y=eval('np.random.normal(16,4,size=[InstanceNoInClass//2,2])')
Y=np.concatenate([Y,YY])
A=Y[:,0]
B=Y[:,1]
plt.scatter(A,B,marker='*',c='red',label='class B')

X=np.concatenate([y,Y])
z=['positive']*InstanceNoInClass
c=['negative']*InstanceNoInClass
Z=np.concatenate([z,c])



SVC_model = svm.SVC(kernel='linear',probability=True)
SVCR_model= svm.SVC(kernel='rbf',probability=True)
KNN_model = KNeighborsClassifier(n_neighbors=3)
NB_model = GaussianNB()
decisionTree_model=DecisionTreeClassifier()
svmForBagging=svm.SVC(kernel='rbf')
RandFor = RandomForestClassifier(random_state=0)
GradBoost= GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, random_state=0)
bagging_model=BaggingClassifier(base_estimator=KNN_model)



kf.get_n_splits(X)
OSVCGMean=0; OSVCRGMean=0; OKNNGMean=0; ONBGMean=0; ODecisionTreeGMean=0; OBaggingGMean=0; OBoostingGMean=0; OrandForGMean=0
OSVCAcc=0; OSVCRAcc=0; OKNNAcc=0; ONBAcc=0; ODecisionTreeAcc=0; OBaggingAcc=0; OBoostingAcc=0; OrandForAcc=0
OSVCAUC=0; OSVCRAUC=0; OKNNAUC=0; ONBAUC=0; ODecisionTreeAUC=0; OBaggingAUC=0; OBoostingAUC=0; OrandForAUC=0

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Z[train_index], Z[test_index]


    SVC_model.fit(X_train, y_train)
    SVCR_model.fit(X_train, y_train)
    KNN_model.fit(X_train, y_train)
    NB_model.fit(X_train, y_train)
    bagging_model.fit(X_train, y_train)
    RandFor.fit(X_train, y_train)
    GradBoost.fit(X_train, y_train)
    decisionTree_model.fit(X_train,y_train)


    SVC_prediction = SVC_model.predict(X_test)
    SVCR_prediction = SVCR_model.predict(X_test)
    KNN_prediction = KNN_model.predict(X_test)
    NB_prediction=NB_model.predict(X_test)
    Bagging_prediction=bagging_model.predict(X_test)
    decisionTree_prediction=decisionTree_model.predict(X_test)
    Randfor_prediction=RandFor.predict(X_test)
    Boosting_Prediction=GradBoost.predict(X_test)


    SVCGMean, SVCAcc,SVCAUC=getGMeanAccAUC(y_test,SVC_prediction,SVC_model.predict_proba(X_test)[:, 1])
    SVCRGMean,SVCRAcc, SVCRAUC=getGMeanAccAUC(y_test,SVCR_prediction,SVCR_model.predict_proba(X_test)[:, 1])
    KNNGMean,KNNAcc,KNNAUC=getGMeanAccAUC(y_test,KNN_prediction,KNN_model.predict_proba(X_test)[:, 1])
    NBGMean,NBAcc,NBAUC=getGMeanAccAUC(y_test,NB_prediction,NB_model.predict_proba(X_test)[:, 1])
    DecisionTreeGMean,DecisionTreeAcc,DecisionTreeAUC=getGMeanAccAUC(y_test,decisionTree_prediction,decisionTree_model.predict_proba(X_test)[:, 1])
    BaggingGMean,BaggingAcc,BaggingAUC=getGMeanAccAUC(y_test,Bagging_prediction,bagging_model.predict_proba(X_test)[:, 1])
    RandforGMean,RandforAcc,RandforAUC=getGMeanAccAUC(y_test,Randfor_prediction,RandFor.predict_proba(X_test)[:, 1])
    BoostingGMean,BoostingAcc,BoostingAUC=getGMeanAccAUC(y_test,Boosting_Prediction,GradBoost.predict_proba(X_test)[:, 1])


    OSVCGMean=OSVCGMean+SVCGMean; OSVCRGMean=OSVCRGMean+SVCRGMean; OKNNGMean=OKNNGMean+KNNGMean; ONBGMean=ONBGMean+NBGMean; ODecisionTreeGMean=ODecisionTreeGMean+DecisionTreeGMean; OBaggingGMean=OBaggingGMean;+BaggingGMean ;OBoostingGMean=OBoostingGMean+BoostingGMean; OrandForGMean=OrandForGMean+RandforGMean;
    OSVCAcc=OSVCAcc+SVCAcc; OSVCRAcc=OSVCRAcc+SVCRAcc; OKNNAcc=OKNNAcc+KNNAcc; ONBAcc=ONBAcc+NBAcc; ODecisionTreeAcc=ODecisionTreeAcc+DecisionTreeAcc; OBaggingAcc=OBaggingAcc+BaggingAcc; OBoostingAcc=OBoostingAcc+BoostingAcc; OrandForAcc=OrandForAcc+BoostingAcc
    OSVCAUC=OSVCAUC+SVCAUC; OSVCRAUC=OSVCRAUC+SVCRAUC; OKNNAUC=OKNNAUC+KNNAUC; ONBAUC=ONBAUC+NBAUC; ODecisionTreeAUC=ODecisionTreeAUC+DecisionTreeAUC; OBaggingAUC=OBaggingAUC+BaggingAUC; OBoostingAUC=OBoostingAUC+BoostingAUC; OrandForAUC=OrandForAUC+BoostingAUC


OSVCGMean=OSVCGMean/5; OSVCRGMean=OSVCRGMean/5; OKNNGMean=OKNNGMean/5; ONBGMean=ONBGMean/5; ODecisionTreeGMean=ODecisionTreeGMean/5; OBaggingGMean=OBaggingGMean/5 ;OBoostingGMean=OBoostingGMean/5; OrandForGMean=OrandForGMean/5;
OSVCAcc=OSVCAcc/5; OSVCRAcc=OSVCRAcc/5; OKNNAcc=OKNNAcc/5; ONBAcc=ONBAcc/5; ODecisionTreeAcc=ODecisionTreeAcc/5; OBaggingAcc=OBaggingAcc/5; OBoostingAcc=OBoostingAcc/5; OrandForAcc=OrandForAcc/5
OSVCAUC=OSVCAUC/5; OSVCRAUC=OSVCRAUC/5; OKNNAUC=OKNNAUC/5; ONBAUC=ONBAUC/5; ODecisionTreeAUC=ODecisionTreeAUC/5; OBaggingAUC=OBaggingAUC/5; OBoostingAUC=OBoostingAUC/5; OrandForAUC=OrandForAUC/5

print('Accuracy of Different Models')
print('svm:',OSVCAcc,OSVCGMean,OSVCAUC)
print('svm-rbf:',OSVCRAcc,OSVCRGMean,OSVCRAUC)
print('knn :',OKNNAcc,OKNNGMean,OKNNAUC)
print('Naive Bayes :',ONBAcc,ONBGMean,ONBAUC)
print('Decision Tree :',ODecisionTreeAcc,ODecisionTreeGMean,ODecisionTreeAUC)
print('Random Forest :',OrandForAcc,OrandForGMean,OrandForAUC)
print('Bagging :',OBaggingAcc,OBaggingGMean,OBaggingAUC)
print('Boosting :',OBoostingAcc,OBoostingGMean,OBoostingAUC)


plt.show()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random

datasize=200
InstanceNoInClass=datasize//2;
np.random.normal()
y=eval('np.random.normal(5,1,size=[InstanceNoInClass,2])')
yy=eval('np.random.normal(16,1,size=[InstanceNoInClass,2])')
y=np.concatenate([y,yy])

A=y[:,0]
B=y[:,1]
plt.scatter(A,B,marker='*',label='class A')

Y=eval('np.random.normal(10,1,size=[InstanceNoInClass,2])')

A=Y[:,0]
B=Y[:,1]
plt.scatter(A,B,marker='*',c='red',label='class B')

Y=np.concatenate([y,Y])
z=[' positive']*InstanceNoInClass*2
c=[' negative']*InstanceNoInClass
z=np.concatenate([z,c])
#dataToClusters(Y,z,label=[' positive',' negative'],nC=2,k=3)
findGMeanOfModels(Y,z)
plt.show()

from sklearn.metrics import AUCuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from statistics import mean

def findGMeanOfModels(X,Z):

  kf = KFold(n_splits=5)
  SVC_model = svm.SVC(kernel='linear')
  KNN_model = KNeighborsClassifier(n_neighbors=3)
  NB_model = GaussianNB()
  regressor = RandomForestClassifier(random_state=0)
  LogReg_model=LogisticRegression(random_state=0)
  decisionTree_model=DecisionTreeClassifier()
  Bagging_model = BaggingClassifier(base_estimator=decisionTree_model,n_estimators=10, random_state=0)
  Boosting_model = GradientBoostingClassifier(n_estimators=10, learning_rate=1.0,max_depth=1, random_state=0)
  SVCRBF=svm.SVC(kernel='rbf')
  SVCGMean=[];KNNGMean=[];NBGMean=[];DecisionTreeGMean=[];SVCRBFGMean=[];RandForestGMean=[];LogRegGMean=[];BaggingGMean=[];BoostingGMean=[];

  for train_index, test_index in kf.split(X):
    X_train, y_train = XYZForTrainTest(X,Z,list(train_index))
    X_test, y_test = XYZForTrainTest(X,Z,list(test_index))
    SVC_model.fit(X_train, y_train)
    SVCRBF.fit(X_train,y_train)
    regressor.fit(X_train,y_train)
    LogReg_model.fit(X_train,y_train)
    KNN_model.fit(X_train, y_train)
    NB_model.fit(X_train, y_train)
    decisionTree_model.fit(X_train,y_train)
    Bagging_model.fit(X_train,y_train)
    Boosting_model.fit(X_train,y_train)


    SVC_prediction = SVC_model.predict(X_test)
    KNN_prediction = KNN_model.predict(X_test)
    NB_prediction=NB_model.predict(X_test)
    decisionTree_prediction=decisionTree_model.predict(X_test)
    SVCRBF_prediction=SVCRBF.predict(X_test)
    RandForest_prediction=regressor.predict(X_test)
    LogReg_prediction=LogReg_model.predict(X_test)
    Bagging_prediction=Bagging_model.predict(X_test)
    Boosting_prediction=Boosting_model.predict(X_test)


    SVCGMean.append(accuracy_score(SVC_prediction, y_test))
    KNNGMean.append(accuracy_score(KNN_prediction, y_test))
    NBGMean.append(accuracy_score(NB_prediction, y_test))
    DecisionTreeGMean.append(accuracy_score(decisionTree_prediction, y_test))
    SVCRBFGMean.append(accuracy_score(SVCRBF_prediction,y_test))
    RandForestGMean.append(accuracy_score(RandForest_prediction,y_test))
    LogRegGMean.append(accuracy_score(LogReg_prediction,y_test))
    BaggingGMean.append(accuracy_score(Bagging_prediction,y_test))
    BoostingGMean.append(accuracy_score(Boosting_prediction,y_test))


  print('Accuracy of Different Models')
  print('svm:',SVCGMean,mean(SVCGMean))
  print('svm-rbf:',SVCRBFGMean,mean(SVCRBFGMean))
  print('knn :',KNNGMean,mean(KNNGMean))
  print('Naive Bayes :',NBGMean,mean(NBGMean))
  print('Decision Tree :',DecisionTreeGMean,mean(DecisionTreeGMean))
  print('Random Forest :',RandForestGMean,mean(RandForestGMean))
  print('Logistic Regression :',LogRegGMean,mean(LogRegGMean))
  print('Bagging :',BaggingGMean,mean(BaggingGMean))
  print('Boosting :',BoostingGMean,mean(BoostingGMean))

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
from google.colab import files as FILE

datasize=200
InstanceNoInClass=datasize//2;
np.random.normal()
y=eval('np.random.normal(4,1,size=[InstanceNoInClass,2])')
yy=eval('np.random.normal(16,1,size=[InstanceNoInClass,2])')
y=np.concatenate([y,yy])

A=y[:,0]
B=y[:,1]
plt.scatter(A,B,marker='^',color='black',label='class A')

Y=eval('np.random.normal(10,1,size=[InstanceNoInClass,2])')
A=Y[:,0]
B=Y[:,1]
plt.scatter(A,B,marker='*',color='black',label='class B')

Y=np.concatenate([y,Y])
z=[' positive']*InstanceNoInClass*2
c=[' negative']*InstanceNoInClass*2
z=np.concatenate([z,c])
plt.legend()
plt.savefig('MultiConcept.eps',dpi=1200,format='eps')
FILE.download('MultiConcept.eps')
plt.show()
plt.close()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
from google.colab import files as FILE

datasize=200
InstanceNoInClass=datasize//2;
np.random.normal()
y=eval('np.random.normal(4,2,size=[InstanceNoInClass,2])')
yy=eval('np.random.normal(16,4,size=[InstanceNoInClass,2])')
y=np.concatenate([y,yy])

A=y[:,0]
B=y[:,1]
plt.scatter(A,B,marker='^',color='black',label='class A')

Y=eval('np.random.normal(16,4,size=[InstanceNoInClass,2])')


A=Y[:,0]
B=Y[:,1]
plt.scatter(A,B,marker='*',color='grey',label='class B')

Y=np.concatenate([y,Y])
z=[' positive']*InstanceNoInClass*2
c=[' negative']*InstanceNoInClass*2
z=np.concatenate([z,c])
plt.legend()
plt.savefig('SyntheticDataF3j.eps',dpi=1200,format='eps')
plt.title('Mean,S.D of Class A=4,2 and 16,4 and Class B=16,4')
FILE.download('SyntheticDataF3j.eps')
plt.show()
plt.close()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
from google.colab import files as FILE

datasize=200
InstanceNoInClass=datasize//2;
np.random.normal()
y=eval('np.random.normal(4,2,size=[InstanceNoInClass,2])')
yy=eval('np.random.normal(16,4,size=[InstanceNoInClass,2])')
y=np.concatenate([y,yy])


A=y[:,0]
B=y[:,1]
plt.scatter(A,B,marker='^',color='black',label='class A')

Y=eval('np.random.normal(16,4,size=[InstanceNoInClass,2])')




A=Y[:,0]
B=Y[:,1]
plt.scatter(A,B,marker='*',color='grey',label='class B')

Y=np.concatenate([y,Y])
z=[' positive']*InstanceNoInClass*2
c=[' negative']*InstanceNoInClass*2
z=np.concatenate([z,c])
plt.legend()
plt.title('Mean,S.D of Class A=4,2 and 16,4 and B=16,4')
plt.savefig('SyntheticDataF3j.eps',dpi=1200,format='eps')
FILE.download('SyntheticDataF3j.eps')
plt.show()
plt.close()



import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random

Y=[[1,1],[1,3],[4,3],[2,4],[3,1],[4,2],[2,2],[5,4]]
Y=np.array(Y)
z=[' positive']*4
c=[' negative']*4
z=np.concatenate([z,c])
dataToClusters(Y,z,label=[' positive',' negative'],nC=2,k=3)



import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random

datasize=200
InstanceNoInClass=datasize//2;
normlist1=['0,5','0,10','0,2','3,5'];
normlist2=['12,5','15,2','15,2','1,5'];
#normlist1=['0,5'];
#normlist2=['15,5'];
fig,ax = plt.subplots(nrows=2, ncols=4,figsize=(25,10))
plotNo=0


#for different mean,SD

for norm1,norm2 in zip(normlist1,normlist2):
  x=list(range(1,datasize+1))
  plotNo=plotNo+1
  plt.subplot(2,4,plotNo)
  #for class A
  np.random.normal()
  y=eval('np.random.normal('+ norm1+',size=[InstanceNoInClass,2])')
  A=np.zeros(InstanceNoInClass)
  B=np.zeros(InstanceNoInClass)
  for i in range(InstanceNoInClass):
     A[i]=y[i,0]
     B[i]=y[i,1]
  plt.title('Mean,SD '+norm1+' '+norm2)
  plt.scatter(A,B,marker='*',c='green',label='class A')

  #for Class B
  b=eval('np.random.normal('+ norm2+',size=[InstanceNoInClass,2])')
  for i in range(InstanceNoInClass):
     A[i]=b[i,0]
     B[i]=b[i,1]
  plt.scatter(A,B,marker='*',c='red',label='class B')


  Y=np.concatenate([y,b])
  z=['Class A']*InstanceNoInClass
  c=['Class B']*InstanceNoInClass
  z=np.concatenate([z,c]);
  newX=np.zeros(datasize)
  newY=np.zeros(datasize)
  for i in range(datasize):
     newX[i]=Y[i,0]
     newY[i]=Y[i,1]


#dataset with different number of concepts
#class A with 1 concept, Class B with 2 concepts
#for class A
plotNo=plotNo+1
plt.subplot(2,4,plotNo)
plt.title('Mean,SD :A=5,2  B=0,2 and 10,2')
y=eval('np.random.normal(5,2,size=[InstanceNoInClass//2,2])')
A=y[:,0]
B=y[:,1]
plt.scatter(A,B,marker='*',c='green',label='class A')

#for Class B
b=eval('np.random.normal(0,2,size=[InstanceNoInClass,2])')
y1=eval('np.random.normal(10,2,size=[InstanceNoInClass//2,2])')
yshow=np.concatenate([b,y1])
A=yshow[:,0]
B=yshow[:,1]
plt.scatter(A,B,marker='*',c='red',label='class B')





#class A with 1 concept, Class B with 2 concepts
#for class A
plotNo=plotNo+1
plt.subplot(2,4,plotNo)
plt.title('Mean,SD :A=5,2  B=8,2 and 15,2')
y=eval('np.random.normal(5,2,size=[InstanceNoInClass//2,2])')
A=y[:,0]
B=y[:,1]
plt.scatter(A,B,marker='*',c='green',label='class A')

#for Class B
b=eval('np.random.normal(8,2,size=[InstanceNoInClass,2])')
y1=eval('np.random.normal(15,2,size=[InstanceNoInClass//2,2])')
yshow=np.concatenate([b,y1])
A=yshow[:,0]
B=yshow[:,1]
plt.scatter(A,B,marker='*',c='red',label='class B')



#class A,B with 2 concepts linearly separable

#for class A
plotNo=plotNo+1
plt.subplot(2,4,plotNo)
plt.title('Mean,SD :A=3,2 and 10,2  B=15,2 and 26,2')
y=eval('np.random.normal(3,2,size=[InstanceNoInClass//2,2])')
y1=eval('np.random.normal(10,2,size=[InstanceNoInClass//2,2])')
yshow=np.concatenate([y,y1])
A=yshow[:,0]
B=yshow[:,1]
plt.scatter(A,B,marker='*',c='green',label='class A')

#for Class B
b=eval('np.random.normal(18,2,size=[InstanceNoInClass,2])')
b1=eval('np.random.normal(26,2,size=[InstanceNoInClass,2])')
b=np.concatenate((b,b1))
A=b[:,0]
B=b[:,1]
plt.scatter(A,B,marker='*',c='red',label='class B')


#class A,B with 2 concepts linearly separable

#for class A
plotNo=plotNo+1
plt.subplot(2,4,plotNo)
plt.title('Mean,SD :A=3,2 and 15,2  B=10,2 and 26,2')
y=eval('np.random.normal(3,2,size=[InstanceNoInClass//2,2])')
y1=eval('np.random.normal(15,2,size=[InstanceNoInClass//2,2])')
yshow=np.concatenate([y,y1])
A=yshow[:,0]
B=yshow[:,1]
plt.scatter(A,B,marker='*',c='green',label='class A')

#for Class B
b=eval('np.random.normal(10,2,size=[InstanceNoInClass,2])')
b1=eval('np.random.normal(26,2,size=[InstanceNoInClass,2])')
b=np.concatenate((b,b1))
A=b[:,0]
B=b[:,1]
plt.scatter(A,B,marker='*',c='red',label='class B')




#plt.suptitle('Sampling from Normal Distributions with different mean,SD',fontsize=20)
plt.subplots_adjust(left=0.1,
                    bottom=0.1,
                    right=0.9,
                    top=0.9,
                    wspace=0.4,
                    hspace=0.4)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random

InstanceNoInClass=20
plt.title('Mean,SD :A=3,2 and 15,2  B=10,2 and 26,2')
y=eval('np.random.normal(3,2,size=[InstanceNoInClass//2,2])')
y1=eval('np.random.normal(15,2,size=[InstanceNoInClass//2,2])')
print(y)
print(y1)
yshow=np.concatenate([y,y1])
print(yshow)
A=yshow[:,0]
B=yshow[:,1]
plt.scatter(A,B,marker='*',c='green',label='class A')
plt.show()

"""# Data to  Clusters"""

from sklearn.cluster import OPTICS
from sklearn.cluster import KMeans
import numpy as np
def dataToClusters(X,Z,label,nC,k):
  #Minority=df[df['Z']==label[0]]
  #Majority=df[df['Z']==label[1]]
  ClassA=[]
  ClassB=[]
  for i in range(len(X)):
    if Z[i]==Z[0]:
      ClassA.append(X[i])
    else:
      ClassB.append(X[i])
  K = range(1,10)
  distortionsA = []
  distortionsB = []
  for k in K:
    kmeanModelA = KMeans(n_clusters=k)
    kmeanModelB = KMeans(n_clusters=k)
    kmeanModelA.fit(ClassA)
    kmeanModelB.fit(ClassB)
    distortionsA.append(kmeanModelA.inertia_)
    distortionsB.append(kmeanModelB.inertia_)
  ratioA=[0]*len(distortionsA)
  for r in range(len(distortionsA)-1):
    ratioA[r]=distortionsA[r]/distortionsA[r+1]
  ratioB=[0]*len(distortionsB)
  for r in range(len(distortionsB)-1):
    ratioB[r]=distortionsB[r]/distortionsB[r+1]
  kA=ratioA.index(max(ratioA))+2
  kB=ratioB.index(max(ratioB))+2
  print('No of clusters in A and B',kA,kB)
  clusteringA = KMeans(n_clusters=kA, init='k-means++', max_iter=300, n_init=10, random_state=0).fit(np.array(ClassA))
  clusteringB = KMeans(n_clusters=kB, init='k-means++', max_iter=300, n_init=10, random_state=0).fit(np.array(ClassB))

  print('Original Dataset')
  CalcOriginalDataset(k,ClassA,ClassB)
  print('Multiple clustered Dataset')
  #print(clusteringA.labels_,clusteringB.labels_)
  CalcDis(k,clusteringA.labels_,clusteringB.labels_,ClassA,ClassB)

from sklearn.cluster import OPTICS
from sklearn.cluster import DBSCAN
from sklearn.cluster import KMeans
import numpy as np
def dataToClusters(df,label,nC,k):
  #Minority=df[df['Z']==label[0]]
  #Majority=df[df['Z']==label[1]]
  X= np.array(df.iloc[:, 0:nC])
  Z= np.array(df.iloc[:, nC])

  ClassA=[]
  ClassB=[]
  for i in range(len(X)):
    if Z[i]==Z[0]:
      ClassA.append(X[i])
    else:
      ClassB.append(X[i])
  clusteringA = OPTICS(min_samples=3).fit(np.array(ClassA))
  clusteringB = OPTICS(min_samples=3).fit(np.array(ClassB))
  print('Original Dataset')
  CalcOriginalDataset(k,ClassA,ClassB)
  print('Multiple clustered Dataset')
  CalcDis(k,clusteringA.labels_,clusteringB.labels_,ClassA,ClassB)

def CalcOriginalDataset(k,CA,CB):
  F1=CalcF1(CA,CB)
  F2=CalcF2(CA,CB)
  F3=CalcF3(CA,CB)
  L1=findL1(CA,CB)
  L2=findL2(CA,CB)
  L3=findL3(CA,CB)
  N4=findN4(CA,CB)
  #NN2=N2(k,CA,CB)
  #N3=findN3(CA,CB,k)
  print('Original Dataset','F1','F2','F3','L1','L2','L3','N4',F1,F2,F3,L1,L2,L3,N4)

def CalcDis(k,labelA,labelB,ClassA,ClassB):
  uniqueA=list(set(labelA))
  uniqueB=list(set(labelB))
  sumF1=math.inf
  sumF2=0
  sumF3=math.inf
  ErrL1=0
  ErrL2=0
  ErrL3=0
  ErrN4=0

  for i in uniqueA:
    for j in uniqueB:
      CA = [ClassA[k] for k in range(len(labelA)) if i==labelA[k]]
      CB = [ClassB[k] for k in range(len(labelB)) if j==labelB[k]]
      FF1=CalcF1(CA,CB)
      if sumF1 > FF1:
        sumF1= FF1
      FF3=CalcF3(CA,CB)
      if sumF3 > FF3:
        sumF3= FF3
      LL1=findL1(CA,CB)
      if ErrL1 < LL1:
        ErrL1=LL1
      LL2=findL2(CA,CB)
      if ErrL2 < LL2:
        ErrL2=LL2
      LL3=findL3(CA,CB)
      if ErrL3 < LL3:
        ErrL3=LL3
      NN4=findN4(CA,CB)
      if ErrN4 < NN4:
        ErrN4=NN4


  print('F1,F2,F3,L1,L2,L3,N4:',sumF1,sumF3,ErrL1,ErrL2,ErrL3,ErrN4)

"""# ComparisonOfModels"""

def XYZForTrainTest(X,Z,FinalSubProb):
  arr=[]
  ClassVal=[]
  for j in FinalSubProb:
      arr.append(X[j])
      ClassVal.append(Z[j])
  cval=[1 if c==' positive' else 0 for c in ClassVal]
  return arr,cval

from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from statistics import mean

def findGMeanOfModels(X,Z):

  kf = KFold(n_splits=5)
  SVC_model = svm.SVC(kernel='linear')
  KNN_model = KNeighborsClassifier(n_neighbors=3)
  NB_model = GaussianNB()
  regressor = RandomForestClassifier(random_state=0)
  LogReg_model=LogisticRegression(random_state=0)
  decisionTree_model=DecisionTreeClassifier()
  Bagging_model = BaggingClassifier(base_estimator=decisionTree_model,n_estimators=10, random_state=0)
  Boosting_model = GradientBoostingClassifier(n_estimators=10, learning_rate=1.0,max_depth=1, random_state=0)
  SVCRBF=svm.SVC(kernel='rbf')
  SVCGMean=[];KNNGMean=[];NBGMean=[];DecisionTreeGMean=[];SVCRBFGMean=[];RandForestGMean=[];LogRegGMean=[];BaggingGMean=[];BoostingGMean=[];

  for train_index, test_index in kf.split(X):
    X_train, y_train = XYZForTrainTest(X,Z,list(train_index))
    X_test, y_test = XYZForTrainTest(X,Z,list(test_index))
    SVC_model.fit(X_train, y_train)
    SVCRBF.fit(X_train,y_train)
    regressor.fit(X_train,y_train)
    LogReg_model.fit(X_train,y_train)
    KNN_model.fit(X_train, y_train)
    NB_model.fit(X_train, y_train)
    decisionTree_model.fit(X_train,y_train)
    Bagging_model.fit(X_train,y_train)
    Boosting_model.fit(X_train,y_train)


    SVC_prediction = SVC_model.predict(X_test)
    KNN_prediction = KNN_model.predict(X_test)
    NB_prediction=NB_model.predict(X_test)
    decisionTree_prediction=decisionTree_model.predict(X_test)
    SVCRBF_prediction=SVCRBF.predict(X_test)
    RandForest_prediction=regressor.predict(X_test)
    LogReg_prediction=LogReg_model.predict(X_test)
    Bagging_prediction=Bagging_model.predict(X_test)
    Boosting_prediction=Boosting_model.predict(X_test)


    SVCGMean.append(accuracy_score(SVC_prediction, y_test))
    KNNGMean.append(accuracy_score(KNN_prediction, y_test))
    NBGMean.append(accuracy_score(NB_prediction, y_test))
    DecisionTreeGMean.append(accuracy_score(decisionTree_prediction, y_test))
    SVCRBFGMean.append(accuracy_score(SVCRBF_prediction,y_test))
    RandForestGMean.append(accuracy_score(RandForest_prediction,y_test))
    LogRegGMean.append(accuracy_score(LogReg_prediction,y_test))
    BaggingGMean.append(accuracy_score(Bagging_prediction,y_test))
    BoostingGMean.append(accuracy_score(Boosting_prediction,y_test))


  print('Accuracy of Different Models')
  print('svm:',SVCGMean,mean(SVCGMean))
  #print('svm-rbf:',SVCRBFGMean,mean(SVCRBFGMean))
  print('knn :',KNNGMean,mean(KNNGMean))
  print('Naive Bayes :',NBGMean,mean(NBGMean))
  print('Decision Tree :',DecisionTreeGMean,mean(DecisionTreeGMean))
  print('Random Forest :',RandForestGMean,mean(RandForestGMean))
  print('Logistic Regression :',LogRegGMean,mean(LogRegGMean))
  print('Bagging :',BaggingGMean,mean(BaggingGMean))
  print('Boosting :',BoostingGMean,mean(BoostingGMean))

from sklearn.cluster import OPTICS
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN

import numpy as np
def dataToClusters(X,Z,label,nC,k):
  ClassA=[]
  ClassB=[]
  for i in range(len(X)):
    if Z[i]==Z[0]:
      ClassA.append(X[i])
    else:
      ClassB.append(X[i])
  NoOfInstances=len(X)
  clusteringA = KMeans(n_clusters=2, init='k-means++', max_iter=300, n_init=10, random_state=0).fit(np.array(ClassA))
  clusteringB = KMeans(n_clusters=2, init='k-means++', max_iter=300, n_init=10, random_state=0).fit(np.array(ClassB))


  labelA=clusteringA.labels_
  labelB=clusteringB.labels_
  uniqueA=list(set(labelA))
  uniqueB=list(set(labelB))
  sumF2=0
  sumF3=0
  ErrL1=0
  ErrL2=0
  ErrL3=0
  ErrN4=0
  for i in uniqueA:
    for j in uniqueB:
      CA = [ClassA[k] for k in range(len(labelA)) if i==labelA[k]]
      CB = [ClassB[k] for k in range(len(labelB)) if j==labelB[k]]
      NoOfInstInCluster=len(CA)+len(CB)
      FF2=CalcF2(CA,CB)
      if FF2>= 0.01:
        sumF2= sumF2 + FF2*NoOfInstInCluster/NoOfInstances
        ErrL1=ErrL1+ findL1(CA,CB)*NoOfInstInCluster/NoOfInstances
        ErrL2=ErrL2+ findL2(CA,CB)*NoOfInstInCluster/NoOfInstances
        ErrL3=ErrL3+ findL3(CA,CB)*NoOfInstInCluster/NoOfInstances
        ErrN4=ErrN4+ findN4(CA,CB)*NoOfInstInCluster/NoOfInstances
      FF3=CalcF3(CA,CB)
      sumF3=sumF3+FF3*2

  print(' N4:',ErrN4)
  #print('F2:',sumF2,' F3:',(NoOfInstances-sumF3)/NoOfInstances,' L1:',ErrL1,' L2:',ErrL2,' L3:',ErrL3,' N4:',ErrN4)

  findGMeanOfModels(X,Z)

from sklearn.cluster import OPTICS
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN

import numpy as np
def dataToClusters(X,Z,label,nC,k):
  ClassA=[]
  ClassB=[]
  for i in range(len(X)):
    if Z[i]==Z[0]:
      ClassA.append(X[i])
    else:
      ClassB.append(X[i])
  NoOfInstances=len(X)
  """
  clusteringA = DBSCAN(eps=5,min_samples=8).fit(np.array(ClassA))
  clusteringB = DBSCAN(eps=5,min_samples=8).fit(np.array(ClassB))
  clusteringA = OPTICS(min_samples=3).fit(np.array(ClassA))
  clusteringB = OPTICS(min_samples=3).fit(np.array(ClassB))
  K = range(1,10)
  distortionsA = []
  distortionsB = []
  for k in K:
    kmeanModelA = KMeans(n_clusters=k)
    kmeanModelB = KMeans(n_clusters=k)
    kmeanModelA.fit(ClassA)
    kmeanModelB.fit(ClassB)
    distortionsA.append(kmeanModelA.inertia_)
    distortionsB.append(kmeanModelB.inertia_)
  ratioA=[0]*len(distortionsA)
  for r in range(len(distortionsA)-2):
    ratioA[r]=distortionsA[r]/distortionsA[r+1]
  ratioB=[0]*len(distortionsB)
  for r in range(len(distortionsB)-2):
    ratioB[r]=distortionsB[r]/distortionsB[r+1]
  kA=ratioA.index(max(ratioA))+2
  kB=ratioB.index(max(ratioB))+2

  #clusteringA = KMeans(n_clusters=kA, init='k-means++', max_iter=300, n_init=10, random_state=0).fit(np.array(ClassA))
  #clusteringB = KMeans(n_clusters=kB, init='k-means++', max_iter=300, n_init=10, random_state=0).fit(np.array(ClassB))

  """
  clusteringA = KMeans(n_clusters=2, init='k-means++', max_iter=300, n_init=10, random_state=0).fit(np.array(ClassA))
  clusteringB = KMeans(n_clusters=2, init='k-means++', max_iter=300, n_init=10, random_state=0).fit(np.array(ClassB))


  labelA=clusteringA.labels_
  labelB=clusteringB.labels_
  uniqueA=list(set(labelA))
  uniqueB=list(set(labelB))
  sumF1=math.inf
  sumF2=0
  sumF3=0
  ErrL1=0
  ErrL2=0
  ErrL3=0
  ErrN4=0
  ClusterCount=0
  for i in uniqueA:
    for j in uniqueB:
      CA = [ClassA[k] for k in range(len(labelA)) if i==labelA[k]]
      CB = [ClassB[k] for k in range(len(labelB)) if j==labelB[k]]
      NoOfInstInCluster=len(CA)+len(CB)
      FF1=CalcF1(CA,CB)
      if sumF1 > FF1:
        sumF1= FF1
      FF2=CalcF2(CA,CB)
      if FF2>0.3:
        ClusterCount=ClusterCount+1
        sumF2= sumF2+ FF2
      #if sumF2 <FF2:
        #sumF2=FF2
      FF3=CalcF3(CA,CB)
      if FF3<0.7:
        sumF3= sumF3+ FF3

      #if sumF3 > FF3:
        #sumF3= FF3
      LL1=findL1(CA,CB)
      if ErrL1 < LL1:
        ErrL1=LL1
      LL2=findL2(CA,CB)
      if ErrL2 < LL2:
        ErrL2=LL2
      LL3=findL3(CA,CB)
      if ErrL3 < LL3:
        ErrL3=LL3
      NN4=findN4(CA,CB)
      if ErrN4 < NN4:
        ErrN4=NN4


  print('F1,F2,F3,L1,L2,L3,N4:',sumF1,sumF2/ClusterCount,sumF3/ClusterCount,ErrL1,ErrL2,ErrL3,ErrN4)
  #findGMeanOfModels(X,Z)

from sklearn import metrics
import numpy as np

def getGMean(y_test,y_pred):
# Creating the confusion matrix
  y_pred=list(y_pred)
  conf_matrix = metrics.confusion_matrix(y_test, y_pred)
  print(y_test,y_pred)
  print(conf_matrix)
  if (np.size(conf_matrix)==1):
    GMean=1
  else:
# Assigning columns names
 # conf_matrix_df = pd.DataFrame(conf_matrix, columns = ['Predicted Negative', 'Predicted Positive'],  index = ['Actual Negative', 'Actual Positive'])
# Showing the confusion matrix
    TP = conf_matrix[1][1]
    TN = conf_matrix[0][0]
    FP = conf_matrix[0][1]
    FN = conf_matrix[1][0]
    if TP==0 and FN==0:
      RecallP=0
    else:
      RecallP = (TP / float(TP + FN))
    if TN==0 and FP==0:
      RecallN=0
    else:
      RecallN = (TN / float(TN + FP))
    GMean= (RecallP*RecallN)**0.5
  return GMean

"""# F1"""

import numpy as np
from statistics import mean
import math



def CalcF1(CA,CB):
  F1=0
  dimension=len(CA[0])
  XXA=np.transpose(CA)
  XXB=np.transpose(CB)
  for i in range(dimension):
    XA=XXA[i][:]
    XB=XXB[i][:]
    F=((mean(XA)-mean(XB))**2)/((np.std(XA))**2+(np.std(XB))**2)
    if abs(F)>F1 :
      F1=abs(F)
  return F1

"""# F2"""

def CalcF2(CA,CB):

  overlap=1
  dimension=len(CA[0])
  XXA=np.transpose(CA)
  XXB=np.transpose(CB)
  for i in range(dimension):
    XA=XXA[i][:]
    XB=XXB[i][:]
    MaxAX=max(XA);MaxBX=max(XB);MinAX=min(XA);MinBX=min(XB)
    if (max([MinAX,MinBX])-min([MaxAX,MaxBX])) >= 0:
      overlap=0
    else:
      calcOverlap=(min([MaxAX,MaxBX])-max([MinAX,MinBX]))/(max([MaxAX,MaxBX])-min([MinAX,MinBX]))
      overlap=overlap*calcOverlap
    #print(overlap)
  return overlap

"""# F3"""

def CalcF3(CA,CB):

  FE=0
  minArr=[0]*len(CA[0]-1)
  maxArr=[0]*len(CA[0]-1)
  dimension=len(CA[0])
  XXA=np.transpose(CA)
  XXB=np.transpose(CB)
  for i in range(dimension):
    XA=XXA[i][:]
    XB=XXB[i][:]
    MaxAX=max(XA);MaxBX=max(XB);MinAX=min(XA);MinBX=min(XB)
    minArr[i]=max([MinAX,MinBX])
    maxArr[i]=min([MaxAX,MaxBX])
    if minArr[i] > maxArr[i]:
      FE=1.0
  noOfPoints=0
  if (FE==0):
    noOfPoints=0
    for i in range(len(CA)):
      dim=len(CA[0])
      count=0
      for j in range(dim):
        if CA[i][j]>=minArr[j] and  CA[i][j]<=maxArr[j] :
          count=count+1
        if count==dim:
          noOfPoints=noOfPoints+1
    for i in range(len(CB)):
      dim=len(CB[0])
      count=0
      for j in range(dim-1):
        if CB[i][j]>=minArr[j] and  CB[i][j]<=maxArr[j] :
          count=count+1
        if count==dim:
          noOfPoints=noOfPoints+1
  FE=noOfPoints
  return FE

"""# L1"""

from sklearn import svm
import numpy as np
from sklearn.model_selection import train_test_split

def findL1(CA,CB):

  Z=np.concatenate(([0]*len(CA),[1]*len(CB)))
  X=np.concatenate((CA,CB))
  clf = svm.SVC(kernel='linear')
  X_train, X_test, y_train, y_test = train_test_split(X, Z)
  clf.fit(X_train,y_train)
  pred=clf.predict(X_test)
  val=[1 if y_test[i]==pred[i] else 0 for i in range(len(y_test))]
  Err=1-sum(val)/len(y_test)
  return Err

"""#L2

"""

from sklearn import svm
import numpy as np

def findL2(CA,CB):
  Z=np.concatenate(([0]*len(CA),[1]*len(CB)))
  X=np.concatenate((CA,CB))
  clf = svm.SVC(kernel='linear')
  clf.fit(X,Z)
  pred=clf.predict(X)
  val=[1 if Z[i]==pred[i] else 0 for i in range(len(Z))]
  Err=1-sum(val)/len(Z)
  return Err

"""# L3

"""

import numpy as np
import math
import random
from sklearn import svm

def findL3(CA,CB):

  Z=np.concatenate(([0]*len(CA),[1]*len(CB)))
  X=np.concatenate((CA,CB))
  leng=math.ceil((len(CA)+len(CB))/4)
  CA=np.array(CA)
  CB=np.array(CB)
  TestA=LinearInterP(CA,leng)
  TestB=LinearInterP(CB,leng)
  Z1=np.concatenate(([0]*len(TestA),[1]*len(TestB)))
  X1=[]
  for i in range(len(TestA)):
    X1.append(TestA[i])
  for i in range(len(TestB)):
    X1.append(TestB[i])
  if len(TestA)==0 or len(TestB)==0:
    Err=0
    return Err
  else:
    clf = svm.SVC(kernel='linear')
    clf.fit(X,Z)
    pred=clf.predict(X1)
    val=[1 if Z1[i]==pred[i] else 0 for i in range(len(Z1))]
    Err=1-sum(val)/len(Z1)
  return Err


def LinearInterP(C,leng):
  np.random.shuffle(C)
  Pts=[]
  for i in range(leng):
    ind1=random.randint(0,len(C)-1)
    ind2=random.randint(0,len(C)-1)
    if ind1!=ind2:
      p0=C[ind1]
      p1=C[ind2]
      sub=np.subtract(p1,p0)
      straight_line_function = lambda p: np.add(p0 , [p*s for s in sub ])
      pVal=random.random()
      Pts.append(straight_line_function(pVal))

  return Pts

"""# N4"""

import numpy as np
import math
import random
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier

def findN4(CA,CB):
  Z=np.concatenate(([0]*len(CA),[1]*len(CB)))
  X=np.concatenate((CA,CB))
  leng=math.ceil((len(CA)+len(CB))/4)
  CA=np.array(CA)
  CB=np.array(CB)
  TestA=LinearInterN4(CA,leng)
  TestB=LinearInterN4(CB,leng)
  Z1=np.concatenate(([0]*len(TestA),[1]*len(TestB)))
  X1=[]
  for i in range(len(TestA)):
    X1.append(TestA[i])
  for i in range(len(TestB)):
    X1.append(TestB[i])
  #X1=np.concatenate((TestA,TestB))
  if len(TestA)==0 or len(TestB)==0:
    Err=0
    return Err
  else:
    clf = KNeighborsClassifier(n_neighbors=1)
    clf.fit(X,Z)
    pred=clf.predict(X1)
    val=[1 if Z1[i]==pred[i] else 0 for i in range(len(Z1))]
    Err=1-sum(val)/len(Z1)
    return Err


def LinearInterN4(C,leng):
  np.random.shuffle(C)
  Pts=[]
  for i in range(leng):
    ind1=random.randint(0,len(C)-1)
    ind2=random.randint(0,len(C)-1)
    if ind1!=ind2:
      p0=C[ind1]
      p1=C[ind2]
      sub=np.subtract(p1,p0)
      straight_line_function = lambda p: np.add(p0 , [p*s for s in sub ])
      pVal=random.random()
      Pts.append(straight_line_function(pVal))


  return Pts

"""# N2"""

import numpy as np
import math
def N2(k,CA,CB):

  C=np.concatenate((CA,CB))
  mat=eucMat(C)
  inter=0
  intra=0
  intraList=[]
  interList=[]
  #ClassA
  for i in range(len(CA)-1):
    intraList=kmin(mat[i][0:len(CA)-1],k)
    interList=kmin(mat[i][len(CA):],k-1)
    intra=intra+sum(intraList)
    inter=inter+sum(interList)

  #ClassB
  for i in range(len(CA),len(C)):
    intraList=kmin(mat[i][len(CA):],k)
    interList=kmin(mat[i][0:len(CA)-1],k-1)
    intra=intra+sum(intraList)
    inter=inter+sum(interList)
  N2=intra/inter
  return N2

def kmin(Arr,k):
  Arr=np.sort(Arr)
  return Arr[:k+1]


def eucMat(C):
  a=len(C)
  mat=[[0]*a]*a
  A=[]
  for x in range(a):
    for y in range(a):
      A.append(dist(C[x],C[y]))
      mat[x]=A
    A=[]
  return mat

def dist(C1,C2):
  dist=0
  n=len(C1)
  for i in range(n):
    dist=dist+(C1[i]-C2[i])**2
  dist=math.sqrt(dist)
  return dist

"""# N3"""

from sklearn.model_selection import LeaveOneOut
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
def findN3(CA,CB,k):

  C=np.concatenate((CA,CB))
  zA=['A']*len(CA)
  zB=['B']*len(CB)
  Z=np.concatenate((np.array(zA),np.array(zB)))
  neigh = KNeighborsClassifier(n_neighbors=3)
  l=LeaveOneOut()
  count=0
  l.get_n_splits(C)
  for trainInd,testInd in l.split(C):
    X_train, X_test = C[trainInd], C[testInd]
    y_train, y_test = Z[trainInd], Z[testInd]
    neigh = KNeighborsClassifier(n_neighbors=k)
    neigh.fit(X_train, y_train)
    if neigh.predict(X_test)==y_test:
      count=count+1
  ErrRate=(len(C)-count)/len(C)
  return ErrRate

"""# Rough

"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random



datasize=20
InstanceNoInClass=datasize//2;
np.random.normal()
y=eval('np.random.normal(4,1,size=[4,2])')
yy=eval('np.random.normal(14,1,size=[4,2])')
yy1=eval('np.random.normal(24,1,size=[8,2])')
y=np.concatenate([y,yy,yy1])

A=y[:,0]
B=y[:,1]
plt.scatter(A,B,marker='*',c='green',label='class A')

b1=eval('np.random.normal(4,1,size=[8,2])')
b2=eval('np.random.normal(16,1,size=[8,2])')
#y1=eval('np.random.normal(26,2,size=[InstanceNoInClass//2,2])')

Y=np.concatenate([b1,b2])
A=Y[:,0]
B=Y[:,1]
plt.scatter(A,B,marker='*',c='red',label='class B')

Y=np.concatenate([y,Y])
z=[' positive']*16
c=[' negative']*16
z=np.concatenate([z,c])
dataToClusters(Y,z,label=[' positive',' negative'],nC=2,k=3)
plt.show()

"""# Estimate Accuracy

# Gmean
"""





"""# samp

"""

from sklearn.cluster import KMeans
import numpy as np

def dataToClusters(X,Z,label,nC,k):
  ClassA=[]
  ClassB=[]
  for i in range(len(X)):
    if Z[i]==Z[0]:
      ClassA.append(X[i])
    else:
      ClassB.append(X[i])
  K = range(1,10)
  distortions = []
  ratio=[0]*len(distortions)
  for k in K:
    kmeanModel = KMeans(n_clusters=k)
    kmeanModel.fit(ClassA)
    distortions.append(kmeanModel.inertia_)
  ratio=[0]*len(distortions)
  for r in range(len(distortions)-1):
    ratio[r]=distortions[r]/distortions[r+1]
  print(distortions,ratio,max(ratio))
  k=ratio.index(max(ratio))+2
  print(k,len(ClassA))
  clusteringA = KMeans(n_clusters=k, init='k-means++', max_iter=300, n_init=10, random_state=0).fit(np.array(ClassA))

  print(clusteringA.labels_)